package org.alfresco.rest.model;

import java.util.List;

import org.alfresco.rest.core.IRestModel;
import org.alfresco.utility.model.TestModel;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Generated by 'saspery' on '2022-09-28 06:54' from 'Alfresco Content Services REST API' swagger file
 * Generated from 'Alfresco Content Services REST API' swagger file
 * Base Path {@linkplain /alfresco/api}
 */
public class RestEntitlementsInfoModel extends TestModel implements IRestModel<RestEntitlementsInfoModel>
{
    @JsonProperty(value = "entry")
    RestEntitlementsInfoModel model;

    @Override
    public RestEntitlementsInfoModel onModel()
    {
        return model;
    }


    private int maxUsers;	    

    private int maxDocs;	    

    private boolean isClusterEnabled;	    

    private boolean isCryptodocEnabled;	    

    private boolean isCustomEmbeddedWorkflowEnabled;	    

    public int getMaxUsers()
    {
        return this.maxUsers;
    }

    public void setMaxUsers(int maxUsers)
    {
        this.maxUsers = maxUsers;
    }				

    public int getMaxDocs()
    {
        return this.maxDocs;
    }

    public void setMaxDocs(int maxDocs)
    {
        this.maxDocs = maxDocs;
    }				

    public boolean getIsClusterEnabled()
    {
        return this.isClusterEnabled;
    }

    public void setIsClusterEnabled(boolean isClusterEnabled)
    {
        this.isClusterEnabled = isClusterEnabled;
    }				

    public boolean getIsCryptodocEnabled()
    {
        return this.isCryptodocEnabled;
    }

    public void setIsCryptodocEnabled(boolean isCryptodocEnabled)
    {
        this.isCryptodocEnabled = isCryptodocEnabled;
    }				

    public boolean getIsCustomEmbeddedWorkflowEnabled()
    {
        return this.isCustomEmbeddedWorkflowEnabled;
    }

    public void setIsCustomEmbeddedWorkflowEnabled(boolean isCustomEmbeddedWorkflowEnabled)
    {
        this.isCustomEmbeddedWorkflowEnabled = isCustomEmbeddedWorkflowEnabled;
    }				
}
 
